{% set name = "yoyo-migrations" %}
{% set version = "8.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/yoyo-migrations-{{ version }}.tar.gz
  sha256: 91c92135ad0b29cfbc35de95e8179cd0d323bd1ebc1a8da5b6c402c26713994b

build:
  number: 0
  noarch: python
  entry_points:
    - yoyo = yoyo.scripts.main:main
    - yoyo-migrate = yoyo.scripts.main:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - sqlparse
    - tabulate

test:
  imports:
    - yoyo
    - yoyo.internalmigrations
  commands:
    - pip check
    - yoyo --help
    - yoyo-migrate --help
  requires:
    - pip

about:
  home: https://ollycope.com/software/yoyo/latest/
  summary: Database migrations with SQL
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ok-gitr
